os: Visual Studio 2015

# version format
version: 0.11.2.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

build_script:
- build\build-appveyor.cmd

test:
  assemblies:
    - 'Umbraco.Tests.dll'

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip

deploy:
    # MyGet (Ditto feed) Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/umbraco-ditto/
    symbol_server: https://www.myget.org/F/umbraco-ditto/symbols/api/v2/package
    api_key:
      secure: Q1/4K8VSwr7BjwmKDTef8y5lOc7S+jK9ELuWy67y6OVRpjxmnF9M3Gfs1kT+ir8x
    artifact: /.*\.nupkg/
    on:
      branch: develop

    # MyGet (Umbraco Community feed) Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/umbraco-packages/
    symbol_server: https://www.myget.org/F/umbraco-packages/symbols/api/v2/package
    api_key:
      secure: Q1/4K8VSwr7BjwmKDTef8y5lOc7S+jK9ELuWy67y6OVRpjxmnF9M3Gfs1kT+ir8x
    artifact: /.*\.nupkg/
    on:
      branch: develop

    # GitHub Deployment for releases
  - provider: GitHub
    auth_token:
      secure: pEozEGTqJutQwOidJU6BTB+Ix0NV4vrUnomhfeqheVz4RNwfxjEYLoqR4XabhlPz
    artifact: /.*\.zip/            # upload all Zip packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only

    # NuGet Deployment for releases
  - provider: NuGet
    server: 
    api_key:
      secure: CGzDKxw4QI/z2VSe9ceiYlIabqGXHolgBgVNWWZjVAJ2V5WLF11IFdlp9r5Qp+Sw
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true
