site_name: Ditto

repo_url: https://github.com/leekelleher/umbraco-ditto/tree/develop/docs

pages:
  - 'Introduction': 'index.md'
  - 'Installation': 'install.md'
  - 'Getting started': 'getting-started.md'
  - 'Usage':
    - 'Basic usage': 'usage-basic.md'
    - 'Advanced usage: Attributes': 'usage-advanced-attributes.md'
    - 'Advanced usage: Processors': 'usage-advanced-processors.md'
    - 'Advanced usage: Conversion Handlers': 'usage-advanced-conversionhandlers.md'
    - 'Advanced usage: Lazy Loading': 'usage-advanced-lazyloading.md'
    - 'Advanced usage: Lists': 'usage-advanced-lists.md'
  - 'Upgrading to v0.9.0': 'upgrade-090.md'
